# Generated by Django 3.1.7 on 2021-03-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Propertyh',
        ),
    ]
